Add a SoftHSM-based emulated token; store the root CA keys on it

diff --git a/dev/offline-ca/entrypoint b/dev/offline-ca/entrypoint
--- a/dev/offline-ca/entrypoint
+++ b/dev/offline-ca/entrypoint
@@ -40,6 +40,23 @@ if [ -z "${CA_NAME}" ] ; then
 fi
 
 log "initialising the '${CA_NAME}' certificate authority"
+#unset P11_KIT_SERVER_ADDRESS
+
+if ! [ -z "${P11_KIT_SERVER_ADDRESS}" ] ; then
+	PKCS11_URL="$(p11tool --list-token-urls --provider /usr/lib/$(uname -m)-linux-gnu/pkcs11/p11-kit-client.so)"
+	if [ -z "$PKCS11_URL" ] ; then
+		log "ERROR: unable to find token"
+		exit 10
+	fi
+	if [ -z "$GNUTLS_PIN" ] ; then
+		log "ERROR: GNUTLS_PIN is not set"
+		exit 11
+	fi
+	log "using PKCS#11 token '${PKCS11_URL}'"
+#	p11tool --provider /usr/lib/$(uname -m)-linux-gnu/pkcs11/p11-kit-client.so --list-tokens
+#	p11tool --list-tokens
+#	exit 10
+fi
 
 if ! [ -f ${DB}/openssl.cnf ] ; then
 	log "generating /app/db/openssl.cnf does not exist, generating..."
@@ -90,15 +107,29 @@ if [ -z "${CA_SERIAL}" ] ; then
 	CA_SERIAL=$(cat ${DB}/ca.serial)
 fi
 
-if [ ! -f ${PRIVKEYS}/${CA_NAME}.key.pem ] ; then
+if ! [ -f ${PRIVKEYS}/${CA_NAME}.key.pem ] ; then
 	case "$CA_KEYTYPE" in
 		rsa)
-			log "generating a ${CA_RSA_BITS} bit RSA keypair..."
-			openssl genrsa -out ${PRIVKEYS}/${CA_NAME}.key.pem ${CA_RSA_BITS}
+			if ! [ -z "${P11_KIT_SERVER_ADDRESS}" ] ; then
+				if ! [ -r "${PUBKEYS}/${CA_NAME}.pub.pem" ] ; then
+					log "generating a ${CA_RSA_BITS} bit RSA keypair via PKCS#11..."
+					p11tool --generate-privkey=rsa --mark-private --bits=${CA_RSA_BITS} --outfile=${PUBKEYS}/${CA_NAME}.pub.pem "${PKCS11_URL}" --login --label "${CA_NAME}"
+				fi
+			else
+				log "generating a ${CA_RSA_BITS} bit RSA keypair..."
+				openssl genrsa -out ${PRIVKEYS}/${CA_NAME}.key.pem ${CA_RSA_BITS}
+			fi
 			;;
 		ec)
-			log "generating a ${CA_EC_CURVE} elliptic curve keypair..."
-			openssl ecparam -genkey -name ${CA_EC_CURVE} -out ${PRIVKEYS}/${CA_NAME}.key.pem
+			if ! [ -z "${P11_KIT_SERVER_ADDRESS}" ] ; then
+				if ! [ -r "${PUBKEYS}/${CA_NAME}.pub.pem" ] ; then
+					log "generating a ${CA_EC_CURVE} elliptic curve keypair via PKCS#11..."
+					p11tool --generate-privkey=ecc --mark-private --outfile=${PUBKEYS}/${CA_NAME}.pub.pem "${PKCS11_URL}" --login --label "${CA_NAME}"
+				fi
+			else
+				log "generating a ${CA_EC_CURVE} elliptic curve keypair..."
+				openssl ecparam -genkey -name ${CA_EC_CURVE} -out ${PRIVKEYS}/${CA_NAME}.key.pem
+			fi
 			;;
 		*)
 			log "ERROR: unsupported CA_KEYTYPE '${CA_KEYTYPE}' (expected 'rsa' or 'ec')"
@@ -107,7 +138,7 @@ if [ ! -f ${PRIVKEYS}/${CA_NAME}.key.pem ] ; then
 	esac
 fi
 
-if [ ! -f ${PRIVKEYS}/${CA_NAME}.keyonly.pem ] ; then
+if [ ! -f ${PRIVKEYS}/${CA_NAME}.keyonly.pem ] && [ -f ${PRIVKEYS}/${CA_NAME}.key.pem ]; then
 	case "$CA_KEYTYPE" in
 		rsa)
 			cp ${PRIVKEYS}/${CA_NAME}.key.pem ${PRIVKEYS}/${CA_NAME}.keyonly.pem
@@ -122,12 +153,23 @@ fi
 
 ## XXX check for expiry if the CA certificate is already present
 
+privkey=${PRIVKEYS}/${CA_NAME}.key.pem
+keyopts=""
+cakeyopts=""
+engineopts=""
+if ! [ -z "${P11_KIT_SERVER_ADDRESS}" ] ; then
+	privkey="$(p11tool --list-all "${PKCS11_URL}" | grep "URL: " | grep "=${CA_NAME};" | cut -c7-);pin-value=${GNUTLS_PIN}"
+	keyopts="-keyform engine"
+	cakeyopts="-CAkeyform engine"
+	engineopts="-engine pkcs11"
+fi
+
 if ! [ -r ${CERTS}/${CA_NAME}.crt.pem ] ; then
 	case "${CA_TYPE}" in
 		root)
 			log "generating self-signed root certificate"
 			# Wrap the key in a self-signed certificate using the above configuration
-			openssl req -batch -config ${DB}/openssl.cnf -set_serial 0x${CA_SERIAL} -key ${PRIVKEYS}/${CA_NAME}.key.pem -new -x509 -out ${CERTS}/${CA_NAME}.crt.pem
+			openssl req ${engineopts} -batch -config ${DB}/openssl.cnf -set_serial 0x${CA_SERIAL} -key "${privkey}" ${keyopts} -new -x509 -out ${CERTS}/${CA_NAME}.crt.pem
 			;;
 		sub)
 			if ! [ -r ${REQUESTS}/${CA_NAME}.req.pem ] ; then
@@ -156,7 +198,7 @@ fi
 if ! [ -r ${REQUESTS}/${CA_NAME}.req.pem ] && [ -r ${CERTS}/${CA_NAME}.crt.pem ] ; then
 	# Generate a CSR from the certificate for cross-signing
 	log "generating CSR for ${CA_NAME}"
-	openssl x509 -x509toreq -in ${CERTS}/${CA_NAME}.crt.pem -signkey ${PRIVKEYS}/${CA_NAME}.key.pem -out ${REQUESTS}/${CA_NAME}.req.pem
+	openssl x509 ${engineopts} -x509toreq -in ${CERTS}/${CA_NAME}.crt.pem -signkey "${privkey}" ${keyopts} -out ${REQUESTS}/${CA_NAME}.req.pem
 fi
 
 ## We have both a CA certificate and a private key, we can perform requests
@@ -187,14 +229,15 @@ case "$1" in
 				serial=$( openssl rand -hex 16 )
 				log "generated serial number for '$2' is '${serial}'"
 			fi
-			openssl x509 \
+			set -x
+			openssl x509 ${engineopts} \
 				-sha512 \
 				-req \
 				-extfile ${DB}/openssl.cnf \
 				-extensions ${profile}_extensions \
 				-set_serial 0x${serial} \
 				-CA ${CERTS}/${CA_NAME}.crt.pem \
-				-CAkey ${PRIVKEYS}/${CA_NAME}.key.pem \
+				-CAkey "${privkey}" ${cakeyopts} \
 				-in ${REQUESTS}/$2.req.pem \
 				-out ${CERTS}/$2.${CA_NAME}.crt.pem
 			cat ${CERTS}/$2.${CA_NAME}.crt.pem ${CERTS}/${CA_NAME}.fullchain.pem > ${CERTS}/$2.${CA_NAME}.fullchain.pem
